"""Agregando campo de DNI a cliente

Revision ID: 51bc28a8d2d7
Revises: 
Create Date: 2025-02-19 23:51:08.653859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51bc28a8d2d7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dni', sa.String(length=8), nullable=False))
        batch_op.alter_column('telefono',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=9),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.alter_column('telefono',
               existing_type=sa.String(length=9),
               type_=sa.VARCHAR(length=20),
               existing_nullable=False)
        batch_op.drop_column('dni')

    # ### end Alembic commands ###
