"""Agregando campo dias a cliente

Revision ID: a504a15c9c51
Revises: 51bc28a8d2d7
Create Date: 2025-02-20 02:31:51.558204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a504a15c9c51'
down_revision = '51bc28a8d2d7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.add_column(sa.Column('dias', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cliente', schema=None) as batch_op:
        batch_op.drop_column('dias')

    # ### end Alembic commands ###
